<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Parameters -->
    <xacro:property name="base_length" value="0.5"/>
    <xacro:property name="base_width" value="0.5"/>
    <xacro:property name="base_height" value="0.1"/>
    <xacro:property name="width_offset_tolerance" value="0.008"/> 

    <!-- Derived Parameters -->
    <xacro:property name="joint_offset_width" value="${base_width/2 + wheel_width/2 + width_offset_tolerance}"/>
    <xacro:property name="joint_offset_length" value="${base_length/2}"/>

    <!-- Inertial Macros -->
    <xacro:macro name="inertial_box" params="mass x y z">
        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="${mass/12.0*(y*y + z*z)}" ixy="0.0" ixz="0.0" 
                     iyy="${mass/12.0*(x*x + z*z)}" iyz="0.0" 
                     izz="${mass/12.0*(x*x + y*y)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_cylinder" params="mass r h">
        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="${(1/4.0)*mass*r*r + (1/12.0)*mass*h*h}" ixy="0.0" ixz="0.0"
                     iyy="${(1/4.0)*mass*r*r + (1/12.0)*mass*h*h}" iyz="0.0"
                     izz="${(1/2.0)*mass*r*r}"/>
        </inertial>
    </xacro:macro>

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="10.0" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </link>

    <!-- Wheel Joint Macro -->
    <xacro:macro name="wheel_joint" params="name parent child xyz">
        <joint name="${name}" type="continuous">
            <parent link="${parent}"/>
            <child link="${child}"/>
            <origin xyz="${xyz}" rpy="${3*pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <!-- Wheel Links and Joints -->
    <xacro:mecanum_wheel name="front_left_wheel" roller_angle = "-0.785398"/> <!--Negative Inclination-->
    <xacro:mecanum_wheel name="front_right_wheel" roller_angle = "0.785398"/> <!--Positive Inclination-->    <!-- 45 degrees in radians -->
    <xacro:mecanum_wheel name="rear_left_wheel" roller_angle = "0.785398"/>
    <xacro:mecanum_wheel name="rear_right_wheel" roller_angle = "-0.785398"/>

    <xacro:wheel_joint name="front_left_wheel_joint" parent="base_link" child="front_left_wheel" xyz="${joint_offset_length} ${joint_offset_width} 0"/>
    <xacro:wheel_joint name="front_right_wheel_joint" parent="base_link" child="front_right_wheel" xyz="${joint_offset_length} -${joint_offset_width} 0"/>
    <xacro:wheel_joint name="rear_left_wheel_joint" parent="base_link" child="rear_left_wheel" xyz="-${joint_offset_length} ${joint_offset_width} 0"/>
    <xacro:wheel_joint name="rear_right_wheel_joint" parent="base_link" child="rear_right_wheel" xyz="-${joint_offset_length} -${joint_offset_width} 0"/>

    <!-- Gazebo plugin for mecanum drive -->
    <gazebo>
        <plugin filename="$(find rw_gz_plugins)/../lib/libmecanum_drive.so" name="mecanum_drive" > 
            <robotWidth>${base_width}</robotWidth>
            <robotLength>${base_length}</robotLength>
        </plugin>
    </gazebo>


</robot>
